;; -*-no-byte-compile: t; -*-
(defvar esn-records-help-DAT-5 '(
		("TRANSLATE=" "TRANSLATE=(list)\n \"List\" describes modifications to be made to the contents of  the data file.  It may contain one or more of: TIME/24,II/24 First, the TIME (or II) data item is processed as if  the  option is  not  present.  Then the resulting value is divided by 24. Two decimal places are present in the NONMEM data file.  This  option can be used to convert the units of time from hours to days. Note: With TRANSLATE=(TIME/24), the value of TIME is  divided  by 24,  whether or not day-time translation occurs (i.e., whether or not relative times are being  computed  by  ).  Similarly, with  TRANSLATE=(II/24)`  II  is divided by 24 whether or not \":\" appears in any II data value.")
		("LAST20=" "LAST20=n3\n Override the LAST20 constant in ABLOCK (default: -1). One or two digit years > LAST20 are assumed to be in the 1900's, One or two digit years <=LAST20 are assumed to be in the 2000's. E.g,. suppose LAST20=50. Then two digit years are interpreted  as follows:  00-50=2000-2050  51-99=1951-1999")
		("NOOPEN" "NOOPEN\n will not open the named data file.  This permits the data")
		("REWIND" "REWIND\n These options apply only to a $DATA record in a problem  specification  other  than  the first, and only when the filename is the same as that specified for the previous problem. REWIND: Position the file at the start so that the first   data set in the file is re-used. NOREWIND: Leave the file at its current position so that the next   data  set  in  the  file is used` the previous problem's $DATA record must have included the RECORDS option (or  a  NONMEM FINISH  record  must  have been present in the file), so that  did not read  to  the  physical  end-of-file.  This  is  the default. NONMEM may or may not be instructed to rewind the NONMEM data set depending  if  it  is  reading  from  the file named in the $DATA record or from FDATA` see NONMEM Users Guide, Part IV for a  complete explanation.")
		("NOREWIND" "NOREWIND\n These options apply only to a $DATA record in a problem  specification  other  than  the first, and only when the filename is the same as that specified for the previous problem. REWIND: Position the file at the start so that the first   data set in the file is re-used. NOREWIND: Leave the file at its current position so that the next   data  set  in  the  file is used` the previous problem's $DATA record must have included the RECORDS option (or  a  NONMEM FINISH  record  must  have been present in the file), so that  did not read  to  the  physical  end-of-file.  This  is  the default. NONMEM may or may not be instructed to rewind the NONMEM data set depending  if  it  is  reading  from  the file named in the $DATA record or from FDATA` see NONMEM Users Guide, Part IV for a  complete explanation.")
		("WIDE" "WIDE\n Requests that FDATA contain  single-line  records,  and  that  at least  one  space separate columns.  (Records in FDATA will never be wider than 300 characters.) Provides an extra character for elapsed times, so that  they  can accommodate the number of hours in (approximately) 4166 days with a leading space. May not be coded when the input data file contains more than 9999 records.")
		("NOWIDE" "NOWIDE\n Requests that  attempt  to  limit  FDATA  to  80-character records.   Space  between  adjacent columns may be suppressed and multi-line records may be generated.  This is the default.")
		("NULL=" "NULL=c2\n Specifies that null data items in the  data set are to  be replaced  in  the  NONMEM  data  set  by the character c2.  E.g., NULL=0 or NULL=.. Null data items consist of a single dot (.) or  consecutive  commas.   c  may  be  any  character except space (\" \") or semicolon (\"`\"). Also permitted: NULL='c' or NULL=\"c\", where c may be any  character. If this option is omitted,   replaces  each  null  with  a space.")
		("IGNORE=" "IGNORE=c1\n Specifies that any data record having the character c in column 1 should  be ignored, i.e., dropped from the NONMEM data set.  This allows comment records to be included in the  data set. Also permitted: IGNORE='c' or IGNORE=\"c\",  where  c  may  be  any character except space. IGNORE=# is the default. IGNORE=@ signifies that any  data  record  having  an  alphabetic character  or  @  as  its  first non-blank character (not just in column 1) should  be  ignored.   Alphabetic  characters  are  the letters  A-Z  and  a-z.   This permits a table file having header lines to be used as an  data set.")
		("LRECL=" "LRECL=n2\n The number of characters in a logical record.  Needed for certain operating systems (e.g., IBM/CMS).")
		("RECORDS=" "RECORDS=n1\n The number of records to be read from the  data  set.   If omitted,  records are read to the end of file or to a NONMEM FINISH record.  ")
		("NRECS=" "NRECS=n1\n The number of records to be read from the  data  set.   If omitted,  records are read to the end of file or to a NONMEM FINISH record.  ")
		("RECS=" "RECS=n1\n The number of records to be read from the  data  set.   If omitted,  records are read to the end of file or to a NONMEM FINISH record.  ")
		("NRECORDS=" "NRECORDS=n1\n The number of records to be read from the  data  set.   If omitted,  records are read to the end of file or to a NONMEM FINISH record.  ")
		("(format)" "(format)\n FORTRAN format specification to be used to read the data.  Format codes  F, E, and X may be used, but not I.  When a format is provided, the label DROP cannot be used on  the  $INPUT  record  and options WIDE and NULL may not be coded.  If omitted,  will generate a suitable FORMAT specification.")
)

"* $DATA help for NONMEM 5")

(provide 'esn-records-help-DAT-5)

(provide 'esn-nm-cookies-help-DAT-5)
