;; -*-no-byte-compile: t; -*-
(defvar esn-records-help-EST-6 '(
		("OMITTED" "OMITTED\n The Estimation Step is not implemented.")
		("NOSBOUNDTEST" "NOSBOUNDTEST\n Instructs NONMEM to omit the \"default  boundary  test\"  for  this type  of  variable, i.e., to behave like NONMEM V in this regard. Any option listed above may be  preceded  by  \"NO\".   The  THETA, OMEGA, and SIGMA choices are independent of each other.  E.g., it is possible to specify NOOBT (to prevent the \"default OMEGA boundary test\") and permit both the \"default THETA boundary test\" and \"default SIGMA boundary test\".")
		("NOSBT" "NOSBT\n Instructs NONMEM to omit the \"default  boundary  test\"  for  this type  of  variable, i.e., to behave like NONMEM V in this regard. Any option listed above may be  preceded  by  \"NO\".   The  THETA, OMEGA, and SIGMA choices are independent of each other.  E.g., it is possible to specify NOOBT (to prevent the \"default OMEGA boundary test\") and permit both the \"default THETA boundary test\" and \"default SIGMA boundary test\".")
		("NOSIGMABOUNDTEST" "NOSIGMABOUNDTEST\n Instructs NONMEM to omit the \"default  boundary  test\"  for  this type  of  variable, i.e., to behave like NONMEM V in this regard. Any option listed above may be  preceded  by  \"NO\".   The  THETA, OMEGA, and SIGMA choices are independent of each other.  E.g., it is possible to specify NOOBT (to prevent the \"default OMEGA boundary test\") and permit both the \"default THETA boundary test\" and \"default SIGMA boundary test\".")
		("NOOBOUNDTEST" "NOOBOUNDTEST\n Instructs NONMEM to omit the \"default  boundary  test\"  for  this type  of  variable, i.e., to behave like NONMEM V in this regard. Any option listed above may be  preceded  by  \"NO\".   The  THETA, OMEGA, and SIGMA choices are independent of each other.  E.g., it is possible to specify NOOBT (to prevent the \"default OMEGA boundary test\") and permit both the \"default THETA boundary test\" and \"default SIGMA boundary test\".")
		("NOOBT" "NOOBT\n Instructs NONMEM to omit the \"default  boundary  test\"  for  this type  of  variable, i.e., to behave like NONMEM V in this regard. Any option listed above may be  preceded  by  \"NO\".   The  THETA, OMEGA, and SIGMA choices are independent of each other.  E.g., it is possible to specify NOOBT (to prevent the \"default OMEGA boundary test\") and permit both the \"default THETA boundary test\" and \"default SIGMA boundary test\".")
		("NOOMEGABOUNDTEST" "NOOMEGABOUNDTEST\n Instructs NONMEM to omit the \"default  boundary  test\"  for  this type  of  variable, i.e., to behave like NONMEM V in this regard. Any option listed above may be  preceded  by  \"NO\".   The  THETA, OMEGA, and SIGMA choices are independent of each other.  E.g., it is possible to specify NOOBT (to prevent the \"default OMEGA boundary test\") and permit both the \"default THETA boundary test\" and \"default SIGMA boundary test\".")
		("NOTBOUNDTEST" "NOTBOUNDTEST\n Instructs NONMEM to omit the \"default  boundary  test\"  for  this type  of  variable, i.e., to behave like NONMEM V in this regard. Any option listed above may be  preceded  by  \"NO\".   The  THETA, OMEGA, and SIGMA choices are independent of each other.  E.g., it is possible to specify NOOBT (to prevent the \"default OMEGA boundary test\") and permit both the \"default THETA boundary test\" and \"default SIGMA boundary test\".")
		("NOTBT" "NOTBT\n Instructs NONMEM to omit the \"default  boundary  test\"  for  this type  of  variable, i.e., to behave like NONMEM V in this regard. Any option listed above may be  preceded  by  \"NO\".   The  THETA, OMEGA, and SIGMA choices are independent of each other.  E.g., it is possible to specify NOOBT (to prevent the \"default OMEGA boundary test\") and permit both the \"default THETA boundary test\" and \"default SIGMA boundary test\".")
		("NOTHETABOUNDTEST" "NOTHETABOUNDTEST\n Instructs NONMEM to omit the \"default  boundary  test\"  for  this type  of  variable, i.e., to behave like NONMEM V in this regard. Any option listed above may be  preceded  by  \"NO\".   The  THETA, OMEGA, and SIGMA choices are independent of each other.  E.g., it is possible to specify NOOBT (to prevent the \"default OMEGA boundary test\") and permit both the \"default THETA boundary test\" and \"default SIGMA boundary test\".")
		("SIGMABOUNDTEST" "SIGMABOUNDTEST\n With NONMEM VI, the estimation step sometimes terminates with the message PARAMETER ESTIMATE IS NEAR ITS DEFAULT BOUNDARY. These options request that the \"default boundary  test\"  be  performed for THETA, OMEGA, and SIGMA, respectively.  THETABOUNDTEST  OMEGABOUNDTEST may  also  be coded  OBT or OBOUNDTEST` SIGMABOUNDTEST   These options are the defaults.")
		("OMEGABOUNDTEST" "OMEGABOUNDTEST\n With NONMEM VI, the estimation step sometimes terminates with the message PARAMETER ESTIMATE IS NEAR ITS DEFAULT BOUNDARY. These options request that the \"default boundary  test\"  be  performed for THETA, OMEGA, and SIGMA, respectively.  THETABOUNDTEST  OMEGABOUNDTEST may  also  be coded  OBT or OBOUNDTEST` SIGMABOUNDTEST   These options are the defaults.")
		("THETABOUNDTEST" "THETABOUNDTEST\n With NONMEM VI, the estimation step sometimes terminates with the message PARAMETER ESTIMATE IS NEAR ITS DEFAULT BOUNDARY. These options request that the \"default boundary  test\"  be  performed for THETA, OMEGA, and SIGMA, respectively.  THETABOUNDTEST  OMEGABOUNDTEST may  also  be coded  OBT or OBOUNDTEST` SIGMABOUNDTEST   These options are the defaults.")
		("TBOUNDTEST" "TBOUNDTEST\n With NONMEM VI, the estimation step sometimes terminates with the message PARAMETER ESTIMATE IS NEAR ITS DEFAULT BOUNDARY. These options request that the \"default boundary  test\"  be  performed for THETA, OMEGA, and SIGMA, respectively.  THETABOUNDTEST  OMEGABOUNDTEST may  also  be coded  OBT or OBOUNDTEST` SIGMABOUNDTEST   These options are the defaults.")
		("TBT" "TBT\n With NONMEM VI, the estimation step sometimes terminates with the message PARAMETER ESTIMATE IS NEAR ITS DEFAULT BOUNDARY. These options request that the \"default boundary  test\"  be  performed for THETA, OMEGA, and SIGMA, respectively.  THETABOUNDTEST  OMEGABOUNDTEST may  also  be coded  OBT or OBOUNDTEST` SIGMABOUNDTEST   These options are the defaults.")
		("SBOUNDTEST" "SBOUNDTEST\n With NONMEM VI, the estimation step sometimes terminates with the message PARAMETER ESTIMATE IS NEAR ITS DEFAULT BOUNDARY. These options request that the \"default boundary  test\"  be  performed for THETA, OMEGA, and SIGMA, respectively.  THETABOUNDTEST  OMEGABOUNDTEST may  also  be coded  OBT or OBOUNDTEST` SIGMABOUNDTEST   These options are the defaults.")
		("SBT" "SBT\n With NONMEM VI, the estimation step sometimes terminates with the message PARAMETER ESTIMATE IS NEAR ITS DEFAULT BOUNDARY. These options request that the \"default boundary  test\"  be  performed for THETA, OMEGA, and SIGMA, respectively.  THETABOUNDTEST  OMEGABOUNDTEST may  also  be coded  OBT or OBOUNDTEST` SIGMABOUNDTEST   These options are the defaults.")
		("SORT" "SORT\n Individual contribution to the objective function value and individual  contributions to the gradients are sorted before they are summed, so that smaller numbers are summed before larger numbers.")
		("NOSORT" "NOSORT\n Individual contribution to the objective function value and individual  contributions to the gradients are summed in the order in which the individual records appear in the NONMEM  data  set,  as was done prior to NONMEM VI.  This is the default.")
		("ETABARCHECK" "ETABARCHECK\n There is an etabar statistic (See etabar) from a  previous  problem, and the P-value associated for the etabar statistic with the problem at hand relates to a hypothesis test that the true etabar is the same as that with the previous problem.")
		("NOETABARCHECK" "NOETABARCHECK\n The P-value associated  for  the  etabar  statistic  (See etabar) relates  to a hypothesis test that the true etabar is 0.  This is the default.")
		("REPEAT2" "REPEAT2\n The search of  the  second  stage  of  the  Stieltjes  method  is repeated  with  the  initial  estimates being the final estimates from the first search and with new UCP, so that a  UCP  value  of 0.1  now  corresponds  to a final estimate from the first search. May only be used with STIELTJES.")
		("NOREPEAT2" "NOREPEAT2\n The estimate obtained at the end of  the  search  of  the  second stage  of the Stieltjes method is taken to be the final parameter estimate at the second stage. This is the default.  May  only  be used with STIELTJES.")
		("REPEAT1" "REPEAT1\n The search of the first stage of the Stieltjes method is repeated with  the  initial  estimates  being the final estimates from the first search and with new UCP, so that a UCP  value  of  0.1  now corresponds  to a final estimate from the first search.  May only be used with STIELTJES.")
		("NOREPEAT1" "NOREPEAT1\n The estimate obtained at the end of the search of the first stage of  the Stieltjes method is taken to be the final parameter estimate at the first stage. This is the default. May  only  be  used with STIELTJES.")
		("REPEAT" "REPEAT\n The search is repeated with the initial estimates being the final estimates  from  the first search and with new UCP, so that a UCP value of 0.1 now corresponds to a final estimate from  the  first search. Cannot be used with STIELTJES.")
		("NOREPEAT" "NOREPEAT\n The estimate obtained at the end of the  minimization  search  is taken to be the final parameter estimate. This is the default. Cannot be used with STIELTJES.")
		("MSFO=" "MSFO=filename\n A Model Specification File is output to a  file  with  the  given filename.  Filename may not contain embedded spaces.  If filename contains commas, semicolons, or parentheses, then it must be surrounded  by  quotes  ('  or  \").  Filename may also contain equal signs if it is enclosed in quotes. Filename may contain at most 71 characters. If filename is the same as any option of the $ESTIMATION  record, it  must  be enclosed in quotes.  If the $NONPARAMETRIC record is present and also specifies  the  MSFO  option,  the  filename  is required on the record which appears first in the control stream. If filename is present on both, it must  be  the  same.   If  the filename  is  omitted  on  the second of the two records, the MSF option must be the final option on that record.  Default: If  the MSFO option is not used, no MSF is output.\n")
		("NOABORT" "NOABORT\n During the Estimation  Step,  NONMEM  implements  theta-recovery, i.e., attempt to avoid values of theta which result in PRED error return code 1.")
		("ABORT" "ABORT\n During the Estimation Step,  NONMEM  does  not  implement  thetarecovery  when  PRED  sets the error return code to 1.  (The PRED error return code n is set by  the  statement  \"EXIT  n  [k]\"  in abbreviated  code,  or by the statement IERPRD=n in user-supplied code, or by PREDPP when it detects errors.)  This is the default.")
		("PRINT=" "PRINT=n3\n Iteration summaries are printed for the 0th,  every  n3th  iteration,  and  last iteration.  When n3=0, no summaries are printed. Default: 9999 (so that summaries are printed  for  0th  and  last iterations).")
		("MAXEVALS=" "MAXEVALS=n2\n Maximum allowable number of evaluations of the objective function during  the  Estimation Step.  Default: a generous number.  (Each evaluation of the objective function requires  one  pass  through the  data  set.  This  is also referred to as a \"function evaluation.\")  MAXEVALS=-1 may be specified  when  a  $MSFI  record  is present.   It requests that NONMEM re-use the value from the previous run, and is the default with $MSFI. MAXEVAL=0 requests that the Estimation Step be omitted.  This  is useful, for example, with POSTHOC (see above).")
		("SIGDIGITS=" "SIGDIGITS=n1\n Number of significant digits  required  in  the  final  parameter estimate.  Default: 3.  ")
		("NSIGDIGITS=" "NSIGDIGITS=n1\n Number of significant digits  required  in  the  final  parameter estimate.  Default: 3.  ")
		("NOPOSTHOC" "NOPOSTHOC\n Etas are not estimated.  This is the default with METHOD=0.   May not be used with METHOD=1.")
		("POSTHOC" "POSTHOC\n This option may be used when the FO method is  used.   After  the Estimation Step terminates, the eta values are estimated for each individual.  To estimate the etas based on the initial  estimates of THETA, OMEGA, and SIGMA (found either in the control stream or in a model specification file),  also  specify  MAXEVAL=0  (which omits  the  Estimation  Step).   The conditional estimates of the etas are referred to as Conditional Parametric Etas (CPE).")
		("ZERO=" "ZERO=list\n Required with METHOD=HYBRID.  A list of indices  for  etas  which are  fixed  to  zero during the Estimation Step.  \"list\" contains one or more integers.  If more than one, they must be  surrounded by parentheses.  The list must be contained entirely on one line. The indices may be separated by commas or spaces.")
		("NONUMERICAL" "NONUMERICAL\n Requests that second eta-derivatives for the Laplacian method  be computed  by  PRED.  Not permitted with the combination LAPLACIAN and INTERACTION.  Otherwise, this is the default.")
		("NUMERICAL" "NUMERICAL\n Requests that second eta-derivatives for the Laplacian method  be obtained numerically.")
		("NOSLOW" "NOSLOW\n Requests a faster method of computation.   This  is  the  default (but see SLOW)")
		("SLOW=" (
			("1" "SLOW=1\n Same as SLOW.")
			("2" "SLOW=2\n This option is permitted with STIELTJES.")
))
		("SLOW" "SLOW\n Requests a slower method of computation.  Required when either  a mixture model is used along with CENTERING, or NUMERICAL is used. If not present, the option is automatically supplied in these two cases. For problems where NONMEM VI does not behave as well (e.g. yields a  higher  OFV at termination) compared to NONMEM V, inclusion of the SLOW option may sometimes, but not always,  yield  NONMEM  VI results that are similar to NONMEM V.")
		("GRID=" "GRID=(nr,ns,r0,r1)\n Optional. May be used with STIELTJES. For nr, ns, r0, and r1, see the Introduction to Version  VI  2.0. Briefly,  a grid is obtained by first taking the interval [r0,r1] of the length axis and  dividing  this  interval  into  nr  equal subintervals.   ns may be thought of as the number of points in a single quadrant of a  2-dimensional  ellipse  in  n-space.   Constraints are nr<=100, ns<=9999, 0<r0<r1<1.  If r1>.9999, there is no tail region.  nr and  ns  should  be  integers.   The  default values are: GRID=(3,1,.6,.9).")
		("STIELTJES" "STIELTJES\n A set of tentative population estimates are first obtained  using some 1st- or 2nd-order method. A tentative value for the integral (i.e. an area) is obtained. Then numerical integration is used to obtain second-stage estimates. See the Introduction to Version VI 2.0.  Not permitted with METHOD=HYBRID.")
		("NOCENTERING" "NOCENTERING\n Requests that the average conditional estimates of each  eta  not be constrained.  This is the default.")
		("CENTERING" "CENTERING\n Requests that the average conditional estimates of  each  eta  be constrained  to  be  close to 0.  May only be used with METHOD=1. Not permitted with INTERACTION.")
		("NOFO" "NOFO\n Requests that the First-Order Model not be used with METHOD=1 and CENTERING.  This is the default.")
		("FO" "FO\n Requests that the First-Order Model be  used  with  METHOD=1  and CENTERING.  Cannot be used with LAPLACIAN.")
		("-2LOGLIKELIHOOD" "-2LOGLIKELIHOOD\n Indicates that Y (with  abbreviated code)  or  F  (with  a user-supplied  PRED  or  ERROR  code)  is  a -2 log (conditional) likelihood.  All remarks for LIKELIHOOD apply.  ")
		("-2LLIKELIHOOD" "-2LLIKELIHOOD\n Indicates that Y (with  abbreviated code)  or  F  (with  a user-supplied  PRED  or  ERROR  code)  is  a -2 log (conditional) likelihood.  All remarks for LIKELIHOOD apply.  ")
		("LIKELIHOOD" "LIKELIHOOD\n This is designed mainly, but not exclusively, for use  with  noncontinuous  observed responses (\"odd-type data\").  Indicates that Y (with  abbreviated code) or F (with a user-supplied PRED or  ERROR  code) will be set to a (conditional) likelihood.  Upon simulation it will be ignored, and the DV data item will  be  set directly  to  the  simulated  value  in abbreviated or user code. Also etas, if any, are understood to be population etas.  Epsilon variables  and  the  $SIGMA  record may not be used.  The L2 data item may not be used. The CONTR and CCONTR options of the $SUBROUTINES record  may  not  L be used.                                                           L NONMEM cannot obtain the initial estimate for omega.  If the data are  population,  and  MAXEVALS=0  is  not  coded,  then METHOD=1 LAPLACE is required.")
		("PREDICTION" "PREDICTION\n Indicates that Y (with  abbreviated code)  or  F  (with  a user-supplied  PRED  or  ERROR  code)  will serve as a prediction variable, i.e., it will be set to a prediction.  Upon simulation, the  simulated  observation is possibly also being set in Y or F. (However, the DV data item may instead be  set  directly  to  the simulated  observation.)  Also, etas (if any) are population etas only if epsilons also appear.  This is the default.")
		("NOLAPLACIAN" "NOLAPLACIAN\n Do not use the Laplacian method.  This is the default.")
		("LAPLACIAN" "LAPLACIAN\n Use the  Laplacian  method,  in  which  second  derivatives  with respect to eta are used. May only be specified with METHOD=1. Cannot be used with $ABBREVIATED DERIV2=NO.")
		("NOINTERACTION" "NOINTERACTION\n Always set etas to 0 during the  computation  of  the  model  for intraindividual random error.  This is the default.")
		("INTERACTION" "INTERACTION\n The dependence on etas of the model for  intra-individual  random error is preserved in the computation of the objective function. Cannot be used with CENTERING.")
		("METHOD=" (
			("0" "METHOD=[0,ZERO]\n Always set etas to 0 during the computation of the objective function.  Also  called the \"first order (FO) method.\"  This is the default.")
			("ZERO" "METHOD=[0,ZERO]\n Always set etas to 0 during the computation of the objective function.  Also  called the \"first order (FO) method.\"  This is the default.")
			("1" "METHOD=[1,CONDITIONAL]\n Use conditional estimates for the etas during  the  computation  of  the  objective  function.   METHOD=1  (without the LAPLACIAN option) is also called  the  \"first  order  conditional estimation (FOCE) method.\"  The conditional estimates of the etas are referred to as Conditional  Parametric  Etas (CPE).")
			("CONDITIONAL" "METHOD=[1,CONDITIONAL]\n Use conditional estimates for the etas during  the  computation  of  the  objective  function.   METHOD=1  (without the LAPLACIAN option) is also called  the  \"first  order  conditional estimation (FOCE) method.\"  The conditional estimates of the etas are referred to as Conditional  Parametric  Etas (CPE).")
			("HYBRID" "METHOD=HYBRID\n Use  conditional  estimates  for   the   etas   during   the computation of the objective function, with the exception of those etas listed in the ZERO option. Cannot be used with [LAPLACIAN,CENTERING].")
))
)

"* $ESTIMATION help for NONMEM 6")

(provide 'esn-records-help-EST-6)

(provide 'esn-nm-cookies-help-EST-6)
