;; -*-no-byte-compile: t; -*-
(defvar esn-records-help-SIM-6 '(
		("OMITTED" "OMITTED\n The Simulation Step is not implemented.")
		("TRUE=" (
			("INITIAL" "TRUE=INITIAL\n The initial estimates given in the control stream are used as the parameter values (\"true values\") in the simulation, except when a model specification file is input.  When  a  model  specification file  is  input,  the initial estimates with the previous run are used as the parameter values (\"true values\") in  the  simulation, and  the  final  estimates  with the previous run are used as the initial estimates in all tasks other than  the  simulation.   The UCP used with these other tasks are the same as with the previous run.  This is the default.  May not be used with  $MSFI  in  conjunction with SUBPROBLEMS=n (n > 1).")
			("FINAL" "TRUE=FINAL\n An input model specification file must be used.  The final  estimates  with  the  previous  run  are used as the parameter values (\"true values\") in the simulation and as the initial estimates in all  tasks  other  than  the  simulation. The UCP used with these other tasks are new, so that a UCP value of 0.1  now  corresponds to a final estimate from the previous run.")
			("PRIOR" "TRUE=PRIOR\n The values stored in common NMPR16 by the PRIOR routine are  used as the true parameter values (\"true values\") in the simulation.")
))
		("NOPREDICTION" "NOPREDICTION\n Permitted only with ONLYSIM. Indicates that the simulated observation will be taken to be  the value to which the DV variable is set.  The code Y=... is permitted inside or outside  a  simulation  block,  but  if  such  code appears in a simulation block, be sure to also include e.g. DV=Y. Also, etas (if any) are understood to be population etas, even if epsilons do not appear.")
		("PREDICTION" "PREDICTION\n Permitted only with ONLYSIM, and is the default. With or without ONLYSIM, unless the  NOPREDICTION  is  used,  the simulated  observation is taken to be the quantity to which the Y variable (with  abbreviated code) or F  variable  (with  a user-supplied  PRED  or  ERROR  routine) is set.  In a simulation block, the DV variable may  be  directly  set  to  the  simulated observation, but the Y (or F) variable should also be set to this observation.  E.g., if a line of code DV=... is used in a simulation  block, be sure to follow this line with the additional line Y=DV.")
		("REQUESTSECOND" "REQUESTSECOND\n NONMEM sets a variable in read-only common ROCM12 informing  PRED whether  or  not PRED needs to compute second-partial derivatives with respect to eta.  Normally, during the Simulation Step, these derivatives  are  not  needed,  either  by NONMEM or by the user. However, the user may want the second-partial eta derivatives  of a  PRED-defined  item and may want the ROCM12 variable to reflect this.  With the REQUESTFIRST option, the ROCM12 variable  is  set so  to  inform PRED that the derivatives need to be computed.  In this case, if an abbreviated code is used to  compute  the  PREDdefined item, the item should not be computed within a simulation block, because  does not  provide  derivatives  for  PREDdefined  items  in  a  simulation  block.   REQUESTSECOND implies REQUESTFIRST.")
		("REQUESTFIRST" "REQUESTFIRST\n NONMEM sets a variable in read-only common ROCM12 informing  PRED whether  or  not  PRED needs to compute first-partial derivatives with respect to eta.  Normally, during the Simulation Step, these derivatives  are  not  needed,  either  by NONMEM or by the user. However, the user may want the first-partial eta derivatives of a PRED-defined  item  and  may  want the ROCM12 variable to reflect this.  With the REQUESTFIRST option, the ROCM12 variable  is  set so  to  inform PRED that the derivatives need to be computed.  In this case, if an abbreviated code is used to  compute  the  PREDdefined item, the item should not be computed within a simulation block, because  does not  provide  derivatives  for  PREDdefined items in a simulation block.")
		("SUBPROBLEMS=" "SUBPROBLEMS=n\n Requests that the entire NONMEM problem is to be repeated n times in  succession  (including all NONMEM steps:  simulation, estimation, covariance, table, scatterplot). Each  subproblem  includes the  Simulation Step, but the random sources are simply continued from subproblem to subproblem.  If n=0 or n=1, there is only  one subproblem`  this  is  the  default.  ")
		("NSUBPROBS=" "NSUBPROBS=n\n Requests that the entire NONMEM problem is to be repeated n times in  succession  (including all NONMEM steps:  simulation, estimation, covariance, table, scatterplot). Each  subproblem  includes the  Simulation Step, but the random sources are simply continued from subproblem to subproblem.  If n=0 or n=1, there is only  one subproblem`  this  is  the  default.  ")
		("NSUBPROBLEMS=" "NSUBPROBLEMS=n\n Requests that the entire NONMEM problem is to be repeated n times in  succession  (including all NONMEM steps:  simulation, estimation, covariance, table, scatterplot). Each  subproblem  includes the  Simulation Step, but the random sources are simply continued from subproblem to subproblem.  If n=0 or n=1, there is only  one subproblem`  this  is  the  default.  ")
		("SUBPROBS=" "SUBPROBS=n\n Requests that the entire NONMEM problem is to be repeated n times in  succession  (including all NONMEM steps:  simulation, estimation, covariance, table, scatterplot). Each  subproblem  includes the  Simulation Step, but the random sources are simply continued from subproblem to subproblem.  If n=0 or n=1, there is only  one subproblem`  this  is  the  default.  ")
		("ONLYSIMULATION" "ONLYSIMULATION\n NONMEM is being asked to simulate data but  not  to  evaluate  an objective function on these data. WRES values in tables and scatterplots will be 0.  PRED-defined data items in tables and  scatterplots  will  be computed using simulated etas and initial thetas. $ESTIM, $COV and $NONP cannot be used with ONLYSIMULATION.  Also, see the PREDICTION and NOPREDICTION options.")
		("NEW" "NEW\n If the NEW option  is  used,  the  vector  of  eta's  (epsilon's) changes  with  each  call to SIMETA (SIMEPS), rather than only at the start of the next individual record (next level-two record).")
		("NONPARAMETRIC" "NONPARAMETRIC\n The random numbers from the first source defined  with  the  NONPARAMETRIC  attribute are used to generate realizations of random vectors from a (multivariate) nonparametric distribution on  eta, obtained  from  the Nonparametric Step of an earlier problem.  An input MSF must also be present.  It is understood that  the  etas are  to  be  simulated from the nonparametric distribution rather than from the  pseudo-normal  distribution  associated  with  the first  source.   The  NONPARAMETRIC attribute can only be used in the definition of the second or subsequent source.")
		("UNIFORM" "UNIFORM\n The random numbers of the source are to be pseudo-uniform on  the interval [0,1].")
		("NORMAL" "NORMAL\n The random numbers of the source are  to  be  pseudo-normal  with mean 0 and variance 1 (unless the source is the first and used to generate  eta  and  epsilon  realizations,  in  which  case   the variance-covariance  of  these variables is that specified in the $OMEGA and $SIGMA records).  This is the default.")
)

"* $SIMULATION help for NONMEM 6")

(provide 'esn-records-help-SIM-6)

(provide 'esn-nm-cookies-help-SIM-6)
