;; -*-no-byte-compile: t; -*-
(defvar esn-records-help-EST-7 '(
		("OMITTED" "OMITTED\n The Estimation Step is not implemented.")
		("NOLABEL=" "NOLABEL=[0,1]\n 1 indicates that the row of item names for FILE will not be written, otherwise 0, the default.")
		("NOTITLE=" "NOTITLE=[0,1]\n 1 indicates the header for FILE will not be written, otherwise 0, the default.")
		("FORMAT=" "FORMAT=s3\n s3  defines the delimiter [,|s(pace)|t(ab)] followed by a Fortran format specification for FILE. The default is s1PE11.4.")
		("FILE=" "FILE=filename\n Parameter  estimates and objective function value will be printed to this file every printed iteration as indicated  by  the  PRINT option.")
		("CALPHA=" "CALPHA=n24\n n24  is  a  value between 0.01 and 0.05.  Alpha error rate to use for linear regression test to  assess  statistical  significance. Default is 0.05.")
		("CITER=" "CITER=n23\n n23  is  the  number  of latest PRINT  or CINTERVAL iterations on which to perform a  linear  regression  test  (where  independent variable  is  iteration  number,  dependent variable is parameter value).  If CITER=10, then 10 of the most recent PRINTed or  CINTERVAL  iterations  are  used  for  the  linear  regression test. CITER=10 is the default.    If CINTERVAL is not specified, then the PRINT setting is used.")
		("CNSAMP=" "CNSAMP=n23\n n23  is  the  number  of latest PRINT  or CINTERVAL iterations on which to perform a  linear  regression  test  (where  independent variable  is  iteration  number,  dependent variable is parameter value).  If CITER=10, then 10 of the most recent PRINTed or  CINTERVAL  iterations  are  used  for  the  linear  regression test. CITER=10 is the default.    If CINTERVAL is not specified, then the PRINT setting is used.")
		("CINTERVAL=" "CINTERVAL=n22\n Every n22 iterations is submitted to the convergence test system.")
		("CTYPE=" "CTYPE=[0|1|2|3]\n CTYPE is used to define the termination test to be applied to the burn-in phases for SAEM and BAYES methods and to  the  estimation phases  for  the ITS, IMP, and IMPMAP methods.  CTYPE=0 indicates no termination test, the default.   CTYPE=1  indicates  that  the test  should  be applied to the objective function value, THETA's and SIGMA's but not to the OMEGA's.  CTYPE=2 indicates  that  the test  should be applied to the objective function value, THETA's, SIGMA's and diagonal elements of OMEGA.  CTYPE=3  indicates  that the  test  should  be  applied  to  the objective function value, THETA's, SIGMA's and all OMEGA elements.")
		("GRD=" "GRD=s2\n s2 is a string of [G|N|D|S]'s with  each  symbol  representing  a THETA  parameter  in  numerical order. G indicates that the THETA should be Gibbs sampled. N indicates the THETA should be  sampled using  the  Metropolis-Hasting algorithm. D indicates the program will decide. G and N are used only  with  the  BAYES  method.   S indicates  that  the THETA is being used to model a SIGMA parameter.  This is optional but may improve the speed of  IMP,  IMPMAP and SAEM methods. Default is DDDD...")
		("MUM=" "MUM=s1\n s1 is a string of [M|N|D|X]'s with  each  symbol  representing  a THETA  parameter  in  numerical order. M indicates that the THETA should be Mu  modeled.  N indicates the THETA should  not  be  Mu modeled.  D  indicates  the  program will decide if the parameter should be Mu modeled or not.  X indicates that THETA is  involved in a covariate-dependent mixture model and is required if this is the case. Default is DDDD...")
		("OACCEPT=" "OACCEPT=n21\n Used  only  with the BAYES method. n21 has meaning only for OMEGA sampled by the Metropolis-Hastings  algorithm.   The  scaling  of degrees  of  freedom is adjusted so that samples are accepted n21 fraction of the time. See OSAMPLE_M2=. Default is 0.5.")
		("OSAMPLE_M3=" "OSAMPLE_M3=n20\n Used only with the BAYES method. n20 has meaning only  for  OMEGA sampled  by the Metropolis-Hastings algorithm.  n20 is the number of times in mode 3 that each parameter is  individually  sampled. Default is 0.")
		("OSAMPLE_M2=" "OSAMPLE_M2=n19\n Used only with the BAYES method. n19 has meaning only  for  OMEGA sampled  by the Metropolis-Hastings algorithm.  n19 is the number of times that OMEGA is generated using a Wishart proposal density at  the  present  OMEGA position and degrees of freedom scaled to have samples accepted a particular fraction of the time. If n19 < 0  this  is  done as many times as there are non-fixed OMEGA elements. Default is -1.")
		("OSAMPLE_M1=" "OSAMPLE_M1=n18\n Used  only with the BAYES method. n18 is the number of times each iteration that OMEGA is generated using  the  Metropolis-Hastings algorithm  and a Wishart proposal density that has variance based on the previous samples. If n18  <  0  this  indicates  that  the OMEGA's  are Gibbs sampled using the appropriate Wishart proposal density and other settings are not relevant.  Default is -1.")
		("PACCEPT=" "PACCEPT=n17\n Used only with the BAYES method. n17 has meaning only for population  parameters  sampled  by  the Metropolis-Hastings algorithm. The scaling of variance is adjusted so that samples are  accepted n17 fraction of the time. See PSAMPLE_M2=. Default is 0.5.")
		("PSAMPLE_M3=" "PSAMPLE_M3=n16\n Used only with the BAYES method. n16 has meaning only for population parameters sampled  by  the  Metropolis-Hastings  algorithm. n16 is the number of times in mode 3 that each parameter is individually sampled. Default is 1.")
		("PSAMPLE_M2=" "PSAMPLE_M2=n15\n Used only with the BAYES method. n15 has meaning only for population  parameters  sampled  by  the Metropolis-Hastings algorithm. n15 is the number of times that a vector of THETA's  and  SIGMA's are  generated  using a multivariate normal proposal density that has mean at the present parameter position and variance scaled to have samples accepted a particular fraction of the time. If n15 < 0 this is done as many times  as  there  are  Metropolis-Hastings parameters. Default is -1.")
		("PSAMPLE_M1=" "PSAMPLE_M1=n14\n Used only with the BAYES method. n14n has meaning only for  population  parameters  sampled by the Metropolis-Hastings algorithm. n14 is the number of times that a vector of THETA's  and  SIGMA's are  generated  using a multivariate normal proposal density that has mean/variances based on the previous samples. Default is 1.")
		("NBURN=" "NBURN=n13\n When used with the SAEM method n13 is the maximum number of iterations used to perform the stochastic phase.   Default  is  2000. When  used  with  the  BAYES  method n13 is the maximum number of iterations used to perform the burn-in phase. Default is 4000.")
		("SEED=" "SEED=n12\n The initial seed for the random number  generator  used  for  the Monte-Carlo methods. Default is 14455.")
		("EONLY=" "EONLY=[0|1]\n A value of 1 indicates the IMP objective function should be evaluated  by  performing only the expectation step without advancing the population parameters. Default is 0.")
		("DF=" "DF=n11\n The proposal density is to be a t distribution with  n11  degrees of  freedom.   Default is 0, a normal density.  Used with the IMP and IMPMAP methods.")
		("IACCEPT=" "IACCEPT=n10\n The scaling of OMEGA is adjusted so that samples are accepted n10 fraction  of  the time. Used with the SAEM and BAYES methods. See ISAMPLE_M2. Default is 0.4.")
		("ISAMPLE_M3=" "ISAMPLE_M3=n9\n n9  is the number of mode 3 iterations for the Metropolis-Hasting algorithm for estimating individual parameters in  which  samples are  generated  for each parameter separately. Used with the SAEM and BAYES methods.  Default is 2.")
		("ISAMPLE_M2=" "ISAMPLE_M2=n8\n n8  is the number of mode 2 iterations for the Metropolis-Hasting algorithm for estimating individual parameters using the  current parameter  vector  position  as  mean  and  a  scaled variance of fROMEGA as variance.  Used  with  the  SAEM  and  BAYES  methods. Default is 2.")
		("ISAMPLE_M1=" "ISAMPLE_M1=n7\n n7 is the number of mode 1 iterations for the  Metropolis-Hasting algorithm  for estimating individual parameters using the population means and variances as proposal density. Used with the  SAEM and BAYES methods.  Default is 2.")
		("ISAMPLE=" "ISAMPLE=n6\n When used with the IMP or IMPMAP methods n6 is the number of random samples per subject used for the expectation  step.   Default is 300.  When used with the SAEM or BAYES method n6 is the number of chains used by the Metropolis-Hastings algorithm for  individual  parameter  estimation.  The  default is 2 for SAEM and 1 for BAYES.")
		("NITER=" "NITER=n5\n When used with the ITS, IMP, and IMPMAP methods n5 is the maximum number  of  iterations.  Default  is  50. When used with the SAEM method n5 is the number  of  iterations  for  the  non-stochastic accumulation  phase.  Default  is  1000. When used with the BAYES method n5 is the number of iterations used to obtain the stationary distribution.  Default is 10000.")
		("NOPRIOR=" "NOPRIOR=[0|1]\n A value of 1 indicates the current estimation method  should  not use the prior, otherwise 0. Used in problem with multiple Estimation Steps.")
		("NOSBOUNDTEST" "NOSBOUNDTEST\n Instructs NONMEM to omit the \"default  boundary  test\"  for  this type  of  variable, i.e., to behave like NONMEM V in this regard. Any option listed above may be  preceded  by  \"NO\".   The  THETA, OMEGA, and SIGMA choices are independent of each other.  E.g., it is possible to specify  NOOBT  (to  prevent  the  \"default  OMEGA boundary test\") and permit both the \"default THETA boundary test\" and \"default SIGMA boundary test\".")
		("NOSBT" "NOSBT\n Instructs NONMEM to omit the \"default  boundary  test\"  for  this type  of  variable, i.e., to behave like NONMEM V in this regard. Any option listed above may be  preceded  by  \"NO\".   The  THETA, OMEGA, and SIGMA choices are independent of each other.  E.g., it is possible to specify  NOOBT  (to  prevent  the  \"default  OMEGA boundary test\") and permit both the \"default THETA boundary test\" and \"default SIGMA boundary test\".")
		("NOSIGMABOUNDTEST" "NOSIGMABOUNDTEST\n Instructs NONMEM to omit the \"default  boundary  test\"  for  this type  of  variable, i.e., to behave like NONMEM V in this regard. Any option listed above may be  preceded  by  \"NO\".   The  THETA, OMEGA, and SIGMA choices are independent of each other.  E.g., it is possible to specify  NOOBT  (to  prevent  the  \"default  OMEGA boundary test\") and permit both the \"default THETA boundary test\" and \"default SIGMA boundary test\".")
		("NOOBOUNDTEST" "NOOBOUNDTEST\n Instructs NONMEM to omit the \"default  boundary  test\"  for  this type  of  variable, i.e., to behave like NONMEM V in this regard. Any option listed above may be  preceded  by  \"NO\".   The  THETA, OMEGA, and SIGMA choices are independent of each other.  E.g., it is possible to specify  NOOBT  (to  prevent  the  \"default  OMEGA boundary test\") and permit both the \"default THETA boundary test\" and \"default SIGMA boundary test\".")
		("NOOBT" "NOOBT\n Instructs NONMEM to omit the \"default  boundary  test\"  for  this type  of  variable, i.e., to behave like NONMEM V in this regard. Any option listed above may be  preceded  by  \"NO\".   The  THETA, OMEGA, and SIGMA choices are independent of each other.  E.g., it is possible to specify  NOOBT  (to  prevent  the  \"default  OMEGA boundary test\") and permit both the \"default THETA boundary test\" and \"default SIGMA boundary test\".")
		("NOOMEGABOUNDTEST" "NOOMEGABOUNDTEST\n Instructs NONMEM to omit the \"default  boundary  test\"  for  this type  of  variable, i.e., to behave like NONMEM V in this regard. Any option listed above may be  preceded  by  \"NO\".   The  THETA, OMEGA, and SIGMA choices are independent of each other.  E.g., it is possible to specify  NOOBT  (to  prevent  the  \"default  OMEGA boundary test\") and permit both the \"default THETA boundary test\" and \"default SIGMA boundary test\".")
		("NOTBOUNDTEST" "NOTBOUNDTEST\n Instructs NONMEM to omit the \"default  boundary  test\"  for  this type  of  variable, i.e., to behave like NONMEM V in this regard. Any option listed above may be  preceded  by  \"NO\".   The  THETA, OMEGA, and SIGMA choices are independent of each other.  E.g., it is possible to specify  NOOBT  (to  prevent  the  \"default  OMEGA boundary test\") and permit both the \"default THETA boundary test\" and \"default SIGMA boundary test\".")
		("NOTBT" "NOTBT\n Instructs NONMEM to omit the \"default  boundary  test\"  for  this type  of  variable, i.e., to behave like NONMEM V in this regard. Any option listed above may be  preceded  by  \"NO\".   The  THETA, OMEGA, and SIGMA choices are independent of each other.  E.g., it is possible to specify  NOOBT  (to  prevent  the  \"default  OMEGA boundary test\") and permit both the \"default THETA boundary test\" and \"default SIGMA boundary test\".")
		("NOTHETABOUNDTEST" "NOTHETABOUNDTEST\n Instructs NONMEM to omit the \"default  boundary  test\"  for  this type  of  variable, i.e., to behave like NONMEM V in this regard. Any option listed above may be  preceded  by  \"NO\".   The  THETA, OMEGA, and SIGMA choices are independent of each other.  E.g., it is possible to specify  NOOBT  (to  prevent  the  \"default  OMEGA boundary test\") and permit both the \"default THETA boundary test\" and \"default SIGMA boundary test\".")
		("SIGMABOUNDTEST" "SIGMABOUNDTEST\n With NONMEM VI, the estimation step sometimes terminates with the message PARAMETER ESTIMATE IS NEAR ITS DEFAULT BOUNDARY. These options request that the \"default boundary  test\"  be  performed for THETA, OMEGA, and SIGMA, respectively.  THETABOUNDTEST  OMEGABOUNDTEST may  also  be coded  OBT or OBOUNDTEST` SIGMABOUNDTEST   These options are the defaults.")
		("OMEGABOUNDTEST" "OMEGABOUNDTEST\n With NONMEM VI, the estimation step sometimes terminates with the message PARAMETER ESTIMATE IS NEAR ITS DEFAULT BOUNDARY. These options request that the \"default boundary  test\"  be  performed for THETA, OMEGA, and SIGMA, respectively.  THETABOUNDTEST  OMEGABOUNDTEST may  also  be coded  OBT or OBOUNDTEST` SIGMABOUNDTEST   These options are the defaults.")
		("THETABOUNDTEST" "THETABOUNDTEST\n With NONMEM VI, the estimation step sometimes terminates with the message PARAMETER ESTIMATE IS NEAR ITS DEFAULT BOUNDARY. These options request that the \"default boundary  test\"  be  performed for THETA, OMEGA, and SIGMA, respectively.  THETABOUNDTEST  OMEGABOUNDTEST may  also  be coded  OBT or OBOUNDTEST` SIGMABOUNDTEST   These options are the defaults.")
		("TBOUNDTEST" "TBOUNDTEST\n With NONMEM VI, the estimation step sometimes terminates with the message PARAMETER ESTIMATE IS NEAR ITS DEFAULT BOUNDARY. These options request that the \"default boundary  test\"  be  performed for THETA, OMEGA, and SIGMA, respectively.  THETABOUNDTEST  OMEGABOUNDTEST may  also  be coded  OBT or OBOUNDTEST` SIGMABOUNDTEST   These options are the defaults.")
		("TBT" "TBT\n With NONMEM VI, the estimation step sometimes terminates with the message PARAMETER ESTIMATE IS NEAR ITS DEFAULT BOUNDARY. These options request that the \"default boundary  test\"  be  performed for THETA, OMEGA, and SIGMA, respectively.  THETABOUNDTEST  OMEGABOUNDTEST may  also  be coded  OBT or OBOUNDTEST` SIGMABOUNDTEST   These options are the defaults.")
		("SBOUNDTEST" "SBOUNDTEST\n With NONMEM VI, the estimation step sometimes terminates with the message PARAMETER ESTIMATE IS NEAR ITS DEFAULT BOUNDARY. These options request that the \"default boundary  test\"  be  performed for THETA, OMEGA, and SIGMA, respectively.  THETABOUNDTEST  OMEGABOUNDTEST may  also  be coded  OBT or OBOUNDTEST` SIGMABOUNDTEST   These options are the defaults.")
		("SBT" "SBT\n With NONMEM VI, the estimation step sometimes terminates with the message PARAMETER ESTIMATE IS NEAR ITS DEFAULT BOUNDARY. These options request that the \"default boundary  test\"  be  performed for THETA, OMEGA, and SIGMA, respectively.  THETABOUNDTEST  OMEGABOUNDTEST may  also  be coded  OBT or OBOUNDTEST` SIGMABOUNDTEST   These options are the defaults.")
		("SORT" "SORT\n Individual contribution to the objective function value and individual  contributions to the gradients are sorted before they are summed, so that smaller numbers are summed before larger numbers.")
		("NOSORT" "NOSORT\n Individual contribution to the objective function value and individual contributions to the gradients are summed in the order  in which  the  individual  records appear in the NONMEM data set, as was done prior to NONMEM VI.  This is the default.")
		("ETABARCHECK" "ETABARCHECK\n There is an etabar statistic (See etabar) from a  previous  problem, and the P-value associated for the etabar statistic with the problem at hand relates to a hypothesis test that the true etabar is the same as that with the previous problem.")
		("NOETABARCHECK" "NOETABARCHECK\n The P-value associated  for  the  etabar  statistic  (See etabar) relates  to a hypothesis test that the true etabar is 0.  This is the default.")
		("REPEAT2" "REPEAT2\n The search of  the  second  stage  of  the  Stieltjes  method  is repeated  with  the  initial  estimates being the final estimates from the first search and with new UCP, so that a  UCP  value  of 0.1  now  corresponds  to a final estimate from the first search. May only be used with STIELTJES.")
		("NOREPEAT2" "NOREPEAT2\n The  estimate  obtained  at  the  end of the search of the second stage of the Stieltjes method is taken to be the final  parameter estimate  at  the  second stage. This is the default. May only be used with STIELTJES.")
		("REPEAT1" "REPEAT1\n The search of the first stage of the Stieltjes method is repeated with the initial estimates being the  final  estimates  from  the first  search  and  with  new UCP, so that a UCP value of 0.1 now corresponds to a final estimate from the first search.  May  only be used with STIELTJES.")
		("NOREPEAT1" "NOREPEAT1\n The estimate obtained at the end of the search of the first stage of  the Stieltjes method is taken to be the final parameter estimate at the first stage. This is the default. May  only  be  used with STIELTJES.")
		("REPEAT" "REPEAT\n The search is repeated with the initial estimates being the final estimates from the first search and with new UCP, so that  a  UCP value  of  0.1 now corresponds to a final estimate from the first search.  Cannot be used with STIELTJES.")
		("NOREPEAT" "NOREPEAT\n The  estimate  obtained  at the end of the minimization search is taken to be the final parameter estimate. This  is  the  default. Cannot be used with STIELTJES.")
		("MSFO=" "MSFO=filename\n A  Model  Specification  File  is output to a file with the given filename.  Filename may not contain embedded spaces.  If filename contains commas, semicolons, or parentheses, then it must be surrounded by quotes (' or \").   Filename  may  also  contain  equal signs  if it is enclosed in quotes.  Filename may contain at most 71 characters.  If filename is the same  as  any  option  of  the $ESTIMATION  record, it must be enclosed in quotes.  If the $NONPARAMETRIC record is present and also specifies the MSFO  option, the filename is required on the record which appears first in the control stream.  If filename is present on both, it must  be  the same.   If  the  filename  is  omitted  on  the second of the two records, the MSF option must be the final option on that  record. Default: If the MSFO option is not used, no MSF is output. If  a  MSFO  is  output, then the iteration estimates may also be seen in the original parameterization for those iterations  whose summaries  appear  in intermediate printout.  These estimates may be found in file INTER. When MAXEVAL=0 and the Covariance Step is implemented,  the  MSFO option may also be used, and then a model specification file will be output which will include information from the Covariance Step and  from  the input model specification file concerning the earlier Estimation Step (in this case there must be an  input  model specification file). (See model_specification_file).")
		("NOABORT" "NOABORT\n During the Estimation  Step,  NONMEM  implements  theta-recovery, i.e., attempt to avoid values of theta which result in PRED error return code 1.  In addition, terminations due to  a  non-positive Hessian matrix for an indivdiual are minimized.")
		("ABORT" "ABORT\n During  the  Estimation  Step,  NONMEM  does not implement thetarecovery when PRED sets the error return code to  1.   (The  PRED error  return  code  n  is  set  by the statement \"EXIT n [k]\" in abbreviated code, or by the statement IERPRD=n  in  user-supplied code, or by PREDPP when it detects errors.)  This is the default.")
		("SIGL=" "SIGL=n4\n n4  is  used  to  calculate  the  step-size for finite difference derivatives independent of  the  SIGDIGITS  value.   If  n4=0  or n4=100  then SIGL is ignored and SIGDIGITS is used as in versions prior to NONMEM 7.  SIGL should usually be 2 to 3 times the value of NSIG.  It is not used by the SAEM or BAYES methods.")
		("PRINT=" "PRINT=n3\n Iteration summaries are printed for the 0th,  every  n3th  iteration,  and  last iteration.  When n3=0, no summaries are printed. Default: 9999 (so that summaries are printed  for  0th  and  last iterations).")
		("MAXEVALS=" "MAXEVALS=n2\n Maximum allowable number of evaluations of the objective function during the Estimation Step.  Default: a generous  number.   (Each evaluation  of  the  objective function requires one pass through the data set.  This is also referred to as  a  \"function  evaluation.\")   MAXEVALS=-1  may  be  specified  when a $MSFI record is present.  It requests that NONMEM re-use the value from the  previous run, and is the default with $MSFI. MAXEVAL=0  requests that the Estimation Step be omitted.  This is useful, for example, with POSTHOC (see above).")
		("SIGDIGITS=" "SIGDIGITS=n1\n Number  of  significant  digits  required  in the final parameter estimate.  SIGDIGITS is not  used  by  the  Monte-Carlo  methods. Default: 3.  ")
		("NSIGDIGITS=" "NSIGDIGITS=n1\n Number  of  significant  digits  required  in the final parameter estimate.  SIGDIGITS is not  used  by  the  Monte-Carlo  methods. Default: 3.  ")
		("NOPOSTHOC" "NOPOSTHOC\n Etas are not estimated.  This is the default with METHOD=0.   May not be used with METHOD=1.")
		("POSTHOC" "POSTHOC\n This option may be used when the FO method is  used.   After  the Estimation Step terminates, the eta values are estimated for each individual.  To estimate the etas based on the initial  estimates of THETA, OMEGA, and SIGMA (found either in the control stream or in a model specification file),  also  specify  MAXEVAL=0  (which omits  the  Estimation  Step).   The conditional estimates of the etas are referred to as Conditional Parametric Etas (CPE).")
		("ZERO=" "ZERO=list\n Required with METHOD=HYBRID.  A list of indices  for  etas  which are  fixed  to  zero during the Estimation Step.  \"list\" contains one or more integers.  If more than one, they must be  surrounded by parentheses.  The list must be contained entirely on one line. The indices may be separated by commas or spaces.")
		("NONUMERICAL" "NONUMERICAL\n Requests that second eta-derivatives for the Laplacian method  be computed  by  PRED.  Not permitted with the combination LAPLACIAN and INTERACTION.  Otherwise, this is the default.")
		("NUMERICAL" "NUMERICAL\n Requests  that second eta-derivatives for the Laplacian method be obtained numerically.")
		("NOSLOW" "NOSLOW\n Requests a faster method of computation.   This  is  the  default (but see SLOW)")
		("SLOW=" (
			("1" "SLOW=1\n Same as SLOW.")
			("2" "SLOW=2\n This option is permitted with STIELTJES.")
))
		("SLOW" "SLOW\n Requests a slower method of computation.  Required when either  a mixture model is used along with CENTERING, or NUMERICAL is used. If not present, the option is automatically supplied in these two cases.   For  problems  where  NONMEM  VI does not behave as well (e.g. yields a higher OFV at termination) compared to  NONMEM  V, inclusion of the SLOW option may sometimes, but not always, yield NONMEM VI results that are similar to NONMEM V.")
		("GRID=" "GRID=(nr,ns,r0,r1)\n Optional. May be used with STIELTJES.  For nr, ns,  r0,  and  r1, see  the  Introduction  to  Version  VI  2.0.  Briefly, a grid is obtained by first taking the interval [r0,r1] of the length  axis and dividing this interval into nr equal subintervals.  ns may be thought of as the number of points in  a  single  quadrant  of  a 2-dimensional  ellipse  in  n-space.   Constraints  are  nr<=100, ns<=9999, 0<r0<r1<1.  If r1>.9999, there is no tail  region.   nr and   ns   should   be   integers.    The   default  values  are: GRID=(3,1,.6,.9).")
		("STIELTJES" "STIELTJES\n A set of tentative population estimates are first obtained  using some  1st-  or 2nd-order method.  A tentative value for the integral (i.e. an area) is obtained.  Then numerical  integration  is used  to  obtain second-stage estimates.  See the Introduction to Version VI 2.0.  Not permitted with METHOD=HYBRID.")
		("NOCENTERING" "NOCENTERING\n Requests  that  the average conditional estimates of each eta not be constrained.  This is the default.")
		("CENTERING" "CENTERING\n Requests  that  the  average conditional estimates of each eta be constrained to be close to 0.  May only be  used  with  METHOD=1. Not permitted with INTERACTION.")
		("NOFO" "NOFO\n Requests that the First-Order Model not be used with METHOD=1 and CENTERING.  This is the default.")
		("FO" "FO\n Requests  that  the  First-Order  Model be used with METHOD=1 and CENTERING.  Cannot be used with LAPLACIAN.")
		("-2LOGLIKELIHOOD" "-2LOGLIKELIHOOD\n Indicates that Y (with  abbreviated code)  or  F  (with  a user-supplied PRED or ERROR code) is a -2 log (conditional) likelihood.  All remarks for LIKELIHOOD apply.   May  also  be  coded -2LLIKELIHOOD.")
		("LIKELIHOOD" "LIKELIHOOD\n This  is  designed mainly, but not exclusively, for use with noncontinuous observed responses (\"odd-type data\").  Indicates  that Y (with  abbreviated code) or F (with a user-supplied PRED or ERROR code) will be set to a (conditional)  likelihood.   Upon simulation  it  will be ignored, and the DV data item will be set directly to the simulated value  in  abbreviated  or  user  code. Also etas, if any, are understood to be population etas.  Epsilon variables and the $SIGMA record may not be  used.   The  L2  data item  may not be used.  The CONTR and CCONTR options of the $SUBROUTINES record may not be used.  NONMEM cannot obtain  the  initial  estimate  for omega.  If the data are population, and MAXEVALS=0 is not coded, then METHOD=1 LAPLACE is required.")
		("PREDICTION" "PREDICTION\n Indicates  that  Y  (with   abbreviated code) or F (with a user-supplied PRED or ERROR code)  will  serve  as  a  prediction variable, i.e., it will be set to a prediction.  Upon simulation, the simulated observation is possibly also being set in Y  or  F. (However,  the  DV  data  item may instead be set directly to the simulated observation.)  Also, etas (if any) are population  etas only if epsilons also appear.  This is the default.")
		("NOLAPLACIAN" "NOLAPLACIAN\n Do not use the Laplacian method.  This is the default.")
		("LAPLACIAN" "LAPLACIAN\n Use  the  Laplacian  method,  in  which  second  derivatives with respect to eta are used. May only be specified with METHOD=1.  Cannot be used with $ABBREVIATED DERIV2=NO unless NUMERICAL option is also specified.")
		("NOINTERACTION" "NOINTERACTION\n Always set etas to 0 during the  computation  of  the  model  for intraindividual random error.  This is the default.")
		("INTERACTION" "INTERACTION\n The dependence on etas of the model for  intra-individual  random error  is preserved in the computation of the objective function. Cannot be used with CENTERING.")
		("METHOD=" (
			("0" "METHOD=[0,ZERO]\n Always set etas to 0 during the computation of the objective function.   Also called the \"first order (FO) method.\"  This is the default.")
			("ZERO" "METHOD=[0,ZERO]\n Always set etas to 0 during the computation of the objective function.   Also called the \"first order (FO) method.\"  This is the default.")
			("1" "METHOD=[1,CONDITIONAL]\n Use conditional estimates for the etas during  the  computation  of  the  objective  function.   METHOD=1  (without the LAPLACIAN option) is also called  the  \"first  order  conditional estimation (FOCE) method.\"  The conditional estimates of the etas are referred to as Conditional  Parametric  Etas (CPE).")
			("CONDITIONAL" "METHOD=[1,CONDITIONAL]\n Use conditional estimates for the etas during  the  computation  of  the  objective  function.   METHOD=1  (without the LAPLACIAN option) is also called  the  \"first  order  conditional estimation (FOCE) method.\"  The conditional estimates of the etas are referred to as Conditional  Parametric  Etas (CPE).")
			("HYBRID" "METHOD=HYBRID\n Use  conditional  estimates for the etas during the computation of the objective function, with the exception of  those etas  listed in the ZERO option.  Cannot be used with [LAPLACIAN,CENTERING].")
			("ITS" "METHOD=ITS\n Use the iterative two-stage method.  This  method  evaluates the  conditional  mode  and first order approximation of the conditional variance of parameters of individuals  by  maximizing  the posterior density.  This integration step is the same as used in the FOCE method.  Population parameters  are updated  from  individuals'  conditional mode parameters and their approximate variances by single iteration maximization steps.")
			("IMP" "METHOD=IMP\n Use  the  Monte-Carlo  Importance Sampling Expectation Maximization method.  This method evaluates the conditional mean and variance of parameters of individuals by Monte Carl sampling. It uses the posterior density, which incorporates the likelihood  of  parameters  relative to population means and variances with the individual's observed data.   The  normal density  near the mean or mode of the posterior is used as a proposal density, then weighted according to  the  posterior density as a correction.")
			("IMPMAP" "METHOD=IMPMAP\n Use the Importance Sampling method assisted by Mode a Posteriori (MAP)  estimation.   At  each  iteration,  conditional modes and conditional first order variances are evaluated as in the [ITS,FOCE] method.  These are then used  as  parameters  to  the  multivariate  normal proposal density for the Monte-Carlo importance sampling step.")
			("SAEM" "METHOD=SAEM\n Use the Stochastic  Approximation  Expectation  Maximization method.   As in importance sampling, random samples are generated from normal proposal densities.  However, instead  of always  being  centered at the mean or mode of the posterior density, the proposal density is centered  at  the  previous sample position.")
			("BAYES" "METHOD=BAYES\n Use  the  Markov  Chain Monte Carlo (MCMC) Bayesian Analysis method.  The goal of the MCMC Bayesian analysis is to obtain a  large sample set of probable population parameters. Various summary statistics of the population parameters may then be obtained such as means and confidence ranges.")
			("CHAIN" "METHOD=CHAIN\n Allows  the user to create a series of random initial values of THETAs and OMEGA's, or for reading in initial  population parameters  from a file of rectangular (rows/column) format.")
))
)

"* $ESTIMATION help for NONMEM 7")

(provide 'esn-records-help-EST-7)

(provide 'esn-nm-cookies-help-EST-7)
